### ISSUE TITLE
about the edge(V)

### ISSUE THREAD

**Issue by Yang-Siqi** [rssmith33/Active-Inference-Tutorial-Scripts#1]
https://github.com/rssmith33/Active-Inference-Tutorial-Scripts/blob/20a3c06456dec925a6b2f4bcdf3b1639ed5cfafb/Message_passing_example.m#L190

Hi！
I feel a little confused about this code. Is there should be tau instead of t?

**Comment by rssmith33** [comment]
If I understood the question correctly, the answer is that both t and tau always have the same final value (same final time step T). So there’s no need to specify a different final value for tau.

Hope that helps!

Best,

Ryan

Ryan Smith, PhD
Principal Investigator
Laureate Institute for Brain Research

Research Associate Professor
Oxley College of Health Sciences
University of Tulsa, Tulsa Oklahoma
https://www.laureateinstitute.org/ryan-smith.html
________________________________
From: Yang-Siqi ***@***.***>
Sent: Friday, August 19, 2022 8:14:12 PM
To: rssmith33/Active-Inference-Tutorial-Scripts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rssmith33/Active-Inference-Tutorial-Scripts] about the edge(V) (Issue #1)


[WARNING] This email originated outside of LIBR. Do not click on any links, open attachments, or respond with information unless you recognize the sender and know the content is safe.

https://github.com/rssmith33/Active-Inference-Tutorial-Scripts/blob/20a3c06456dec925a6b2f4bcdf3b1639ed5cfafb/Message_passing_example.m#L186<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frssmith33%2FActive-Inference-Tutorial-Scripts%2Fblob%2F20a3c06456dec925a6b2f4bcdf3b1639ed5cfafb%2FMessage_passing_example.m%23L186&data=05%7C01%7Crsmith%40laureateinstitute.org%7Ce19049678a1a4e3b29a908da82494b09%7Cff169993a2d34a4e8df384b2675b9050%7C0%7C0%7C637965548565681337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8VNDb1h%2F4c0iT6ykP9%2B7G5Tv7hUJwqAx47m%2BZq9JT%2FA%3D&reserved=0>

Hi！
I feel a little confused about this code. Is there should be tau instead of t?

**Comment by Yang-Siqi** [comment]
Thanks !
